### ISSUE TITLE
`NoMethodError: undefined method `+' for nil:NilClass` on doggy push

### ISSUE THREAD

**Issue by grollest** [bai/doggy#2]
- What did you do?

  I ran the command `/home/vagrant/.gem/ruby/2.1.6/bin/doggy push 124448`

- What did you expect to happen?

  I expected Doggy to push 124448.json to data dog

- What happened instead?

  Instead, what actually happened was it barfed, see stack trace below 

Error details

    NoMethodError: undefined method `+' for nil:NilClass
      /home/vagrant/.gem/ruby/2.1.6/gems/doggy-0.2.0/lib/doggy/model/monitor.rb:95:in `push'
      /home/vagrant/.gem/ruby/2.1.6/gems/doggy-0.2.0/lib/doggy/model/monitor.rb:16:in `block in upload'
      /home/vagrant/.gem/ruby/2.1.6/gems/doggy-0.2.0/lib/doggy/worker.rb:21:in `call'
      /home/vagrant/.gem/ruby/2.1.6/gems/doggy-0.2.0/lib/doggy/worker.rb:21:in `block (2 levels) in call'
      /home/vagrant/.gem/ruby/2.1.6/gems/thread-0.2.2/lib/thread/pool.rb:67:in `call'
      /home/vagrant/.gem/ruby/2.1.6/gems/thread-0.2.2/lib/thread/pool.rb:67:in `execute'
      /home/vagrant/.gem/ruby/2.1.6/gems/thread-0.2.2/lib/thread/pool.rb:405:in `block (2 levels) in spawn_thread'
      /home/vagrant/.gem/ruby/2.1.6/gems/thread-0.2.2/lib/thread/pool.rb:372:in `loop'
      /home/vagrant/.gem/ruby/2.1.6/gems/thread-0.2.2/lib/thread/pool.rb:372:in `block in spawn_thread'

**Comment by grollest** [comment]
my changes are already in DD so I'm not fussed about this.

**Comment by grollest** [comment]
@bai I was running into other problems and some digging revealed I was using the deprecated Shopify version of this repo, which I suspect is to root cause of this issue as well, so I'm closing this.
